### ISSUE TITLE
Remove UT DB table

### ISSUE THREAD

**Issue by harry1453** [burst-apps-team/burstcoin#136]

**Comment by llybin** [comment]
How you plan to store unconfirmed transactions?

**Comment by harry1453** [comment]
Same way they are currently stored - memory.

The UT DB Table currently does not get used, at all.

**Comment by llybin** [comment]
In ethereum currently UT 66,123, https://etherscan.io/txsPending
Yes we can only dream about it :) But in future may be will need to return store in DB, also now as far as I understand maximum count of UT just 8092 by default. But also by default lifetime of transaction is 24 hours.

And it would be more convenient for explorer to work with database than to get all list of UT, may be thousands, and paginate it.

**Comment by harry1453** [comment]
Transactions can take a theoretical maximum of 1200 bytes in memory (assuming 100% efficient memory use, which is possible). 66000 * 1200 = 79.2MB of memory. I don't think it's an issue..

**Comment by llybin** [comment]
Close
