### ISSUE TITLE
Add field message and expiration in Request BURST QR

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#144]
If create possibility add message on generating request Burst QR, it will be easier integrate in shops and etc.

How I see it:
1. User has items in Cart.
2. He'd like pay by BurstCoin.
3. Shop generate for him QR(all data immutable) with message contained number of his order.
4. User scan or copy it in wallet and pay. Transaction contain number of order. _I think better if message will encrypted. Also can create option when you create request message will be encrypted or not._
5. Shop periodically checks new transactions in shop wallet.
6. When shop see new transaction, he see message which order paid. _It easier implement with not encrypted message, because doesn't needed know passphrase for decrypting message and do it._
7. Also can add expiration of request Burst. Wallet(e.g. phoenix) will see this data on scan and decline request.

![image](https://user-images.githubusercontent.com/5445357/57970004-f811ed80-79a5-11e9-8c74-f3d759dceeba.png)

**Comment by llybin** [comment]
@ohager this one implemented in phoenix?
Do you plan to change brs frontend to phoenix? Support two frontends, also legacy not easy.

**Comment by ohager** [comment]
We have QR support since a few versions already. No, we don't plan to add new features to BRS, exactly because of what you said. A medium to long term strategy is to create more dedicated apps that can interoperate using deeplinks. You may look into [CIP22](https://github.com/burst-apps-team/CIPs/blob/master/cip-0022.md) for details on that

**Comment by ohager** [comment]
Just adding: Expiration is not considered yet
