### ISSUE TITLE
Purchasing in marketplace don't affect balance

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#156]
Goods in market place: https://explorer.burst.devtrue.net/mp/16186669496950425587

Price: 7 Burst

I see two accounts bought it:

https://explorer.burst.devtrue.net/tx/18355887132081482245 - 5 goods
https://explorer.burst.devtrue.net/tx/3552890601093019219 - 1 goods

But value in transactions = 0. Balance of accounts is not affected, only fee.

![image](https://user-images.githubusercontent.com/5445357/58814965-efc9db80-8650-11e9-8515-ccdb9a4a4fa6.png)

![image](https://user-images.githubusercontent.com/5445357/58815216-65ce4280-8651-11e9-8d56-715b4ff5cffe.png)

![image](https://user-images.githubusercontent.com/5445357/58814951-e6407380-8650-11e9-8d51-2e8744524e91.png)

![image](https://user-images.githubusercontent.com/5445357/58815175-50591880-8651-11e9-8308-41a3216b4560.png)

**Comment by harry1453** [comment]
Just tested this on testnet. The transaction amount is 0 but the correct amount is subtracted from the account's balance.

**Comment by llybin** [comment]
Thanks, I will check again with the concrete good on mainnet.
Will be nice see this value in transaction amount, but for old transactions will changed hash sum, right? Not easy to hard-forked it.. But may be extract and fill this Value for clear understanding. Transaction has Bursts, but value of Burst in the transaction zero..
Interesting Block.total_amount contain it or not...

**Comment by harry1453** [comment]
Yes, this will require a HF to change the behaviour. I suspect the block's total amount will also not contain this.
