### ISSUE TITLE
I would like to see transactions from trades

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#158]
Events from trades don't create transactions. 
Balance updates correct. 
But I would like to know why my balance was increased or decreased. I don't see it now.

**Comment by llybin** [comment]
Also with marketplace transactions. Amount in these transaction zero. total_amount in Block is also not touched.

**Comment by harry1453** [comment]
Unfortunately this is a forking change

**Comment by wolfduan** [comment]
How can i get the total capacity of burst network?

**Comment by llybin** [comment]
Would we like create these transactions for a past? Currently migration is not allow to do that, right? Or just say sync from a scratch? The last is simpler, but may in future will needed that

**Comment by harry1453** [comment]
If this was implemented as a fork, it would be from the fork block, as it would be a consensus change.

I wonder if we can use indirect incoming table for this?

**Comment by llybin** [comment]
perhaps, but not sure... Currently we know there only multiouts, so we can select all from there and be sure there only Multiouts. if we will create there record with another type, is it will enought for phoenix e.g. One transaction can't contain both assets and multiouts or some other... So we can mark something there same now, but as explorer developer current structure is not usability for me, I can't select only one type. Even now, I have my own table with more details: sender recipient amount, will be nice extend indirect message also

**Comment by jjos2372** [comment]
Close due to inactivity for more than a year.
