### ISSUE TITLE
LGBT friendly code

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#160]
https://github.com/burst-apps-team/burstcoin/blob/develop/t/lib/BURST/API/RequestTypes.pm#L132

Replace Gays on something other :)

**Comment by harry1453** [comment]
https://github.com/burst-apps-team/burstcoin/commit/9e7c42df334a6a7bbbbb8e1802fd8e21aaf183e9 *sigh*

**Comment by harry1453** [comment]
Closed in #162

**Comment by llybin** [comment]
but you forgot to change "Gays" :)

**Comment by harry1453** [comment]
`Hi Gays` -> `Hi Guys`, a phrase often used (despite "guys" technically being a male reference) with no intended target gender. I think this is OK.
