### ISSUE TITLE
API getPeer return not correct wallet version

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#161]
http://wallet.burstcoin.network:8125/burst?requestType=getPeer&peer=104.248.154.129

``` json
{"state":0,"announcedAddress":"wallet-sg.burst.devtrue.net","shareAddress":true,"downloadedVolume":0,"uploadedVolume":0,"application":null,"version":"v0.0.0","platform":null,"blacklisted":false,"lastUpdated":0,"requestProcessingTime":0}
```
**"version":"v0.0.0"**

https://wallet-sg.burst.devtrue.net/burst?requestType=getBlockchainStatus

``` json
{"application":"BRS","version":"v2.3.0","time":151965512,"lastBlock":"13211309636998159666","cumulativeDifficulty":"60672291024050828257","numberOfBlocks":628313,"lastBlockchainFeeder":"a.storj.eu","lastBlockchainFeederHeight":628312,"isScanning":false,"requestProcessingTime":0}
```
**"version":"v2.3.0"**

Mb reproduced only with peers which announce domain name, not sure.

**Comment by harry1453** [comment]
It's not incorrect, it's the empty value - look how everything else is 0 or null. This is because the peer is disconnected and therefore we do not know its state

**Comment by llybin** [comment]
Got it, thanks. mb better return null or empty string?

**Comment by harry1453** [comment]
Probably better to do so.
