### ISSUE TITLE
Desktop wallet should support viewing Multi-Out payments

### ISSUE THREAD

**Issue by blankey1337** [burst-apps-team/burstcoin#17]
As a user, I want to view my Multi-Out payments (incoming/outgoing) using the Desktop Wallet.

**Comment by Quibus-burst** [comment]
This should be fairly simple to do. It should also be as option in config. maybe on as default but ability to turn it off for silent nodes

**Comment by harry1453** [comment]
@Quibus-burst doing it is fairly simple. Doing it without completely sacrificing the database space savings brought about by the multi-out transactions is the issue. I have a plan though, working on a CIP
