### ISSUE TITLE
Fix Reward Recipient Issue

### ISSUE THREAD

**Issue by blankey1337** [burst-apps-team/burstcoin#18]
Currently, there is a bug in QBundle where setting Reward Recipient fails when the call is made against a remote node. 

Users are shown a success message, which makes this bug even more dubious. We should fix this as it prevents users from mining, and is a very bad user experience.

Looks like it happens only on subsequent attempts. so maybe its the finger print stuff removing duplicates. been going over the changes since 2.2.4. main differences is the peer stuff and the message encryption

**Comment by harry1453** [comment]
Are there steps to reproduce this issue outside of QBundle / is the problem isolated to QBundle or is it a problem with the wallet?

**Comment by felixbrucker** [comment]
For me it also happened outside of qbundle on remote wallets via a webrowser. I only debugged this for a short time but the (remote) wallet will report the transaction as disregarded because it thinks the same tx with a higher or equal fee has already been sent. I haven't gotten further.

**Comment by harry1453** [comment]
Able to reproduce, it's not QBundle's fault.
