### ISSUE TITLE
Two transaction asset at one moment

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#182]
Create new one asset, 100 quantity, wait confirmation.

Make Ask Order Placement 50 and quickly make transfer same asset 100 quantity e.g. to your account. They will be unconfirmed at one moment.

You can see now second transfer transaction in pending still unconfirmed, because double spending: http://explorer.testnet.burst.devtrue.net/
http://wallet.testnet.burst.devtrue.net/

![image](https://user-images.githubusercontent.com/5445357/59675245-16f6e000-91ef-11e9-97cf-4aee93c53bb5.png)

My test account in testnet: http://explorer.testnet.burst.devtrue.net/address/2204796096723891230

I think can reproduce that, if first did transfer and next do an ask order placement. 

Also when I did an ask order placement, available balance of asset was not changed. Need to check double ask order placement.

**Comment by harry1453** [comment]
Will try to reproduce.

**Comment by jjos2372** [comment]
That is how it works, unconfirmed transactions will keep pending if they cannot be fulfilled (no balance or similar).
