### ISSUE TITLE
Windows 10 do endless loop of checking then download BRS 2.4

### ISSUE THREAD

**Issue by shefass** [burst-apps-team/burstcoin#188]
https://cdn.discordapp.com/attachments/491125617664851978/595194868322664467/unknown.png

At windows 10 antimalware service starts endless work then download finishes of BRS 2.4, you need to restart to end this. I think I noticed the same behavior at testnet release, but not understand what is happening

**Comment by harry1453** [comment]
Does this help? https://www.reddit.com/r/Windows10/comments/3iouzd/issue_windows_defender_locking_up_downloaded/

**Comment by shefass** [comment]
![image](https://user-images.githubusercontent.com/39196313/60435474-56bbbf80-9c12-11e9-9aad-2c2943ba0935.png)
Not helped

**Comment by shefass** [comment]
Turning real-time protection helped.

**Comment by harry1453** [comment]
OK. Closing as not an issue with BRS. [VirusTotal Scan](https://www.virustotal.com/gui/url/39e973666c1b44d405b12955d6993cc5583db3691dd55e0b7b8ddbf4cd6c7a2f/detection)
