### ISSUE TITLE
Chinese account alias garbled

### ISSUE THREAD

**Issue by wy414012** [burst-apps-team/burstcoin#198]
2.4.1 Chinese account alias garbled after the upgrade?

**Comment by matbogdan79** [comment]
I have the same problem. I think is the API problem.
check https://explore.burstcoin.ro/account/15759313138355018720
In the DB is correct BMF50POOL.BURSTCOIN.ROᶜˡᵒᵘᵈᶠˡᵃʳᵉ ᵖʳᵒᵗᵉᶜᵗᵉᵈ .
It worked fine on 2.3.0 wallet version.

**Comment by harry1453** [comment]
There is some kind of UTF-8 character filtering going on that needs to be stopped.

**Comment by RNHaoHao** [comment]
BurstCoin 怎么搭建自己的私链

**Comment by harry1453** [comment]
https://github.com/burst-apps-team/burstcoin/commit/b79b2fb010de9a1e76b8b6a15dae0ebc6bddf2ec
