### ISSUE TITLE
Cannot read property 'data' of undefined in transaction

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#204]
Version: 2.4.1
Sometimes I get error in recent transactions: "Cannot read property 'data' of undefined"
I show in screencast how to reproduce it. https://yadi.sk/i/yrfARejwAnDp6g

**Comment by harry1453** [comment]
Am I right in thinking that you've put a message on an ordinary payment? Whilst the network technically supports this, the frontend does not and you have run into the undefined behaviour of the frontend...

**Comment by llybin** [comment]
Sorry for bad explanation. The last transactions are ordinary payments with included messages, in each transaction different types of message. One has not encrypted, other encrypted message, other self message + not encrypted and etc. On video I just click in random order on these transactions and get error. You can find them here: BURST-C35E-9FMD-NUDP-25KSQ

**Comment by harry1453** [comment]
Okay. As I said, the network supports this, but the frontend does not. I will look into this...

**Comment by jjos2372** [comment]
Inactive for too long.
