### ISSUE TITLE
Set fee by default Standard

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#205]
Version: 2.4.1

By default, fee always equal 0.1 Burst. I suggest set Standard by default.

What you think about sort by amount fees? At this moment no sort: standart > cheaper < priority. I suggest cheaper - standard - priority or reverse sort.

![image](https://user-images.githubusercontent.com/5445357/61714523-41573280-ad85-11e9-953f-ec47f8fa3958.png)

![image](https://user-images.githubusercontent.com/5445357/61714540-4ae09a80-ad85-11e9-82f5-b4add820c858.png)

![image](https://user-images.githubusercontent.com/5445357/61714590-6ba8f000-ad85-11e9-9dc1-5a7cf9711735.png)

**Comment by harry1453** [comment]
When you say sort, are you referring to in an API call?

**Comment by llybin** [comment]
In user interface

**Comment by harry1453** [comment]
Oh, I see...

**Comment by jjos2372** [comment]
Fixed, will be on the next release.
