### ISSUE TITLE
using signed long to store unsigned id is a bad idea

### ISSUE THREAD

**Issue by pynixwang** [burst-apps-team/burstcoin#225]
such as account id, transaction id

**Comment by harry1453** [comment]
Why is it a bad idea? We are not performing any arithmetic on it, data is data.

https://stackoverflow.com/a/44413515/2898030

**Comment by pynixwang** [comment]
so log should show as unsigned.

**Comment by harry1453** [comment]
As part of the Kotlin move we are going to try to move to using Kotlin's proper unsigned types.

**Comment by pynixwang** [comment]
@harry1453 kotlin move started?

**Comment by pynixwang** [comment]
@harry1453  I saw you branch
