### ISSUE TITLE
BlockReward in Burst and not in Planck

### ISSUE THREAD

**Issue by ohager** [burst-apps-team/burstcoin#232]
The BRS API endpoint `burst?requestType=getBlock` returns the `blockReward` in Burst. This is kind of inconsistent as amounts usually are returned in Planck  (also denominated by NQT as suffix)

__Example__
```{block: "3488499411810061714", height: 664632, generator: "12758986723875749368",…}
baseTarget: "61156"
block: "3488499411810061714"
blockReward: "437"
blockSignature: "74747d1730a59b50cb3f6a164097fd9787f353f88de8143b9dc63de3a3b76103c3f9e1f1176b55d48f63ae7423d5501ece38b8be1734ed8c565a23fb31e467c2"
generationSignature: "076fd1d8e4475ed5db1fc03529b50bf9ec458488e9437ab98e5a4ca04d5ac688"
generator: "12758986723875749368"
generatorPublicKey: "f2f5ed80b29fa701faf0bc8ff681e4edcb122caf2686ccd2e77a673eeeb3985f"
generatorRS: "BURST-MZHS-UF7A-FPFW-D8A64"
height: 664632
nextBlock: "3125524200688994105"
nonce: "304577562851195527"
numberOfTransactions: 3
payloadHash: "2ba63b740db506c7753003844d8a87e8161d8d6063c6ba9e1b45cc26fc5b57dd"
payloadLength: 603
previousBlock: "4553223426859934269"
previousBlockHash: "3d22f92c954c303f17937f57211b652e148facb7cad42dd2e1f28a5cd40b6d79"
requestProcessingTime: 1
scoopNum: 3415
timestamp: 160745893
totalAmountNQT: "90239662294"
totalFeeNQT: "21000000"
transactions: ["11198718532497238800", "17179261092392357355", "7527346391458987870"]
version: 3```

**Comment by harry1453** [comment]
Yep, this issue has been raised before, and we are restricted by backwards compatibility. Maybe we could add a new field `blockRewardNQT`

We are also looking to ditch the `NQT` suffix in favour of `Planck` but this is also a breaking change.

**Comment by ohager** [comment]
Adding an additional field using _Planck_ suffix is a valid way. So, the other field can be marked as deprecated and removed in a future major version

**Comment by harry1453** [comment]
Yes, this is something to consider.

**Comment by frankTheTank72** [comment]
i think we can close this issue as we have now a min reward of 100

**Comment by jjos2372** [comment]
Closing after CIP29

**Comment by ohager** [comment]
I will reopen, because it's still not solved. @frankTheTank72 The discussion is not about the reward itself, but the inconsistency of returned values. All other endpoints which return values do this in Planck/NQT, with exception of this one. It's a very minor issue, but for sake of consistency we need to address this in the future...
