### ISSUE TITLE
The overview of subscriptions does not seem to correspond to the header columns.

### ISSUE THREAD

**Issue by frankTheTank72** [burst-apps-team/burstcoin#236]
When receiving a subscription, the overview is showing the active subsriptions, but the content does not seem to correspond with the Header columns:

![image](https://user-images.githubusercontent.com/39116221/65377229-9e9a3200-dca9-11e9-87d7-8840806235cb.png)

Please adjust postion of Frequency and NextPayment

**Comment by jjos2372** [comment]
Fixed, will be on the 3.0 release.
