### ISSUE TITLE
Ongoing payments on a subscription use 1 BURST fee - why ?

### ISSUE THREAD

**Issue by frankTheTank72** [burst-apps-team/burstcoin#237]
I created a subscription with min fee setup. I was not asked for any fee i like to pay for the continious  payments because of the new subscription.

![image](https://user-images.githubusercontent.com/39116221/65378029-73b4db80-dcb3-11e9-9554-47059a9aed21.png)

As you can see in the screenshot i paid 1 BURST for the second payment ( 0,00735 for the first )

Question : Should this not be adjusted to the new fee structure ? 
User should get a notification that payments costs 1 BURST; if he can´t change it

Suggestion : 
User should be able to set fee for ongoing payments ; or the fee should be adjsuted to 0.1 BURST

**Comment by frankTheTank72** [comment]
BTW : Cancellation-costs was 0.1 BURST
![image](https://user-images.githubusercontent.com/39116221/65378105-8845a380-dcb4-11e9-853c-4a5944474f68.png)

**Comment by harry1453** [comment]
Duplicate of https://github.com/burst-apps-team/burstcoin/issues/32
