### ISSUE TITLE
p2p api error v3.0.0alpha2

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#271]
curl -X POST "http://wallet.testnet.burst.devtrue.net:7123/burst" -H "User-Agent: BRS/2.3.0" -d '{"protocol": "B1", "requestType": "getPeers"}'    
{"peers":["fitzybits.mynetgear.com",.... - OK

curl -X POST "http://wallet.testnet.burst.devtrue.net:7123/burst" -H "User-Agent: BRS/2.3.0" -d '{"protocol": "B1", "requestType": "getInfo"}' 
{"error":"java.lang.IllegalStateException: JSON: Could not get application"}

curl -X POST "http://wallet.testnet.burst.devtrue.net:7123/burst" -H "User-Agent: BRS/2.3.0" -d '{"protocol": "B1", "requestType": "getCumulativeDifficulty"}'
{"cumulativeDifficulty":"18992015007266218","blockchainHeight":108728}

curl -X POST "http://wallet.testnet.burst.devtrue.net:7123/burst" -H "User-Agent: BRS/2.3.0" -d '{"protocol": "B1", "requestType": "addPeers"}'               
{"error":"java.lang.IllegalStateException: JSON: Could not get peers"}

curl -X POST "http://wallet.testnet.burst.devtrue.net:7123/burst" -H "User-Agent: BRS/2.3.0" -d '{"protocol": "B1", "requestType": "getMilestoneBlockIds"}'
{"error":"java.lang.IllegalStateException: JSON: Could not get lastBlockId"}

curl -X POST "http://wallet.testnet.burst.devtrue.net:7123/burst" -H "User-Agent: BRS/2.3.0" -d '{"protocol": "B1", "requestType": "getNextBlockIds"}'     
{"nextBlockIds":[]}

curl -X POST "http://wallet.testnet.burst.devtrue.net:7123/burst" -H "User-Agent: BRS/2.3.0" -d '{"protocol": "B1", "requestType": "getBlocksFromHeight"}'
{"error":"Unsupported request type!"}

curl -X POST "http://wallet.testnet.burst.devtrue.net:7123/burst" -H "User-Agent: BRS/2.3.0" -d '{"protocol": "B1", "requestType": "getNextBlocks"}'      
{"nextBlocks":[]}

curl -X POST "http://wallet.testnet.burst.devtrue.net:7123/burst" -H "User-Agent: BRS/2.3.0" -d '{"protocol": "B1", "requestType": "getUnconfirmedTransactions"}'
{"unconfirmedTransactions":[]}

curl -X POST "http://wallet.testnet.burst.devtrue.net:7123/burst" -H "User-Agent: BRS/2.3.0" -d '{"protocol": "B1", "requestType": "processBlock"}'              
{"accepted":false}

curl -X POST "http://wallet.testnet.burst.devtrue.net:7123/burst" -H "User-Agent: BRS/2.3.0" -d '{"protocol": "B1", "requestType": "processTransactions"}'
{"error":"java.lang.IllegalStateException: JSON: Could not get transactions"}

curl -X POST "http://wallet.testnet.burst.devtrue.net:7123/burst" -H "User-Agent: BRS/2.3.0" -d '{"protocol": "B1", "requestType": "getAccountBalance"}' - empty response, may be ok, I check quickly

curl -X POST "http://wallet.testnet.burst.devtrue.net:7123/burst" -H "User-Agent: BRS/2.3.0" -d '{"protocol": "B1", "requestType": "getAccountRecentTransactions"}' - same

need to check all requestType or cover by tests

**Comment by harry1453** [comment]
Please note that some of the API calls were deprecated and have subsequently been removed.

Is the only issue `processTransactions`?

**Comment by llybin** [comment]
Right, only these.
