### ISSUE TITLE
v3.0.0alpha2 HTTP ERROR 403 Forbidden

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#272]
http://wallet.testnet.burst.devtrue.net/

![image](https://user-images.githubusercontent.com/5445357/69047992-01e8dc00-0a2f-11ea-9981-ac192cceb3d5.png)

**Comment by shefass** [comment]
This is release build error. Check html/ui folder, it is empty.

2019-11-18, pr, 13:12 Lev Lybin <notifications@github.com> rašė:

**Comment by llybin** [comment]
really html/ui is empty, that's why may be we got 403 but someone copied over previous version

**Comment by llybin** [comment]
I copied statics, works now.

**Comment by shefass** [comment]
Yes, good idea. Works for me too.

2019-11-18, pr, 13:31 Lev Lybin <notifications@github.com> rašė:

**Comment by harry1453** [comment]
Looks like the release ZIP is created before UI folder is copied...
