### ISSUE TITLE
Suggestions for BlockchainProcessorServiceImpl.kt

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#287]
1. [getCommonMilestoneBlockId](https://github.com/burst-apps-team/burstcoin/blob/develop/src/main/kotlin/brs/services/impl/BlockchainProcessorServiceImpl.kt#L408)
// prevent overloading with blockIds
if (milestoneBlockIds.size() > 20)
but [API](https://github.com/burst-apps-team/burstcoin/blob/develop/src/main/kotlin/brs/peer/GetMilestoneBlockIds.kt) return maximum 10, may be create one constant and use in both places?

2. [getCommonBlockId](https://github.com/burst-apps-team/burstcoin/blob/develop/src/main/kotlin/brs/services/impl/BlockchainProcessorServiceImpl.kt#L432)
2.1. before was same checks "// prevent overloading with blocks", now only truncate 1440, I would return this check.
2.2. [API](https://github.com/burst-apps-team/burstcoin/blob/develop/src/main/kotlin/brs/peer/GetNextBlockIds.kt#L20) return maximum 100, same suggestion use constant.
2.3. questions here: https://github.com/burst-apps-team/burstcoin/commit/e76e74ba678ccc7e2ef2efacd589bd42fbec0acd#diff-51e91949db96f24bfaf2b63c3aa68b19L431

3. [getNextBlocks](https://github.com/burst-apps-team/burstcoin/blob/develop/src/main/kotlin/brs/services/impl/BlockchainProcessorServiceImpl.kt#L463) 1440 and max 100 in [API](https://github.com/burst-apps-team/burstcoin/blob/develop/src/main/kotlin/brs/peer/GetNextBlocks.kt#L21) same suggestion use constant.

**Comment by harry1453** [comment]
Additionally, https://github.com/burst-apps-team/burstcoin/commit/e76e74ba678ccc7e2ef2efacd589bd42fbec0acd#r36434460

**Comment by harry1453** [comment]
Regarding 1, it is in case of a peer that is not the same as us. I will think about this..

Regarding 2, it is to avoid discarding *all* of the information if we received more than 1440, I don't see why we should just throw away and start again. Why is truncating worse?

**Comment by llybin** [comment]
Currently, APIs return maximum only 1. 10, 2. 100 and 3. 100. I started to think about it, when I saw loop while(true), what can happens if I will create fake peer, and he always will returns a big amount of data for destabilization network. I didn't take into case when peer is legetimate (but not brs), he really can has other limits. It need to think, but if change something, better change in all places at once.

**Comment by harry1453** [comment]
Another issue is if limits change between BRS versions we don't want to make an upgrade incompatible with the rest of the network.

**Comment by llybin** [comment]
Agree. Then I think, need just review current values in both places, and make similar logic decline or truncate in these functions imho

**Comment by jjos2372** [comment]
This branch is not under development at the moment.
