### ISSUE TITLE
v3.0.0alpha2 high CPU usage

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#295]

**Comment by harry1453** [comment]
This is described [here](https://github.com/burst-apps-team/burstcoin/commit/17ef029090f888be321c60d5d6d3cb3b9a3ada2f#diff-8d60c259c68a9950d9d3efb74a20c0a9R330) and is expected behaviour.

**Comment by llybin** [comment]
**********
SYSTEM INFORMATION
RT: OpenJDK Runtime Environment, Version: 13-ea+32
VM: OpenJDK 64-Bit Server VM, Version: 13-ea+32
OS: Linux, Version: 4.15.0-72-generic, Architecture: amd64
**********

v3.0.0-alpha4

CPU.NumCores = 1
PreVerifier.NumberOfInstances = 1

![image](https://user-images.githubusercontent.com/5445357/71769426-c5782d80-2f53-11ea-8042-8a6d2c15bc4e.png)

I think it's much for testnet, I don't see new blocks or many transactions. Blockchain synced. If compare with 2.4, 3.0 uses more CPU.

**Comment by llybin** [comment]
![image](https://user-images.githubusercontent.com/5445357/71769461-53ecaf00-2f54-11ea-8dc6-fccad97842e4.png)

2.4

**Comment by harry1453** [comment]
Could you make a comparison of sync speed? 3.0 should be faster and use more CPU as it wastes less time waiting for memory & DB operations

**Comment by llybin** [comment]
I saw your improvements, it's cool! But I not checked yet. I launched on existed and synced DB 3.0 version. Above, I compare 2.4 on mainet and 3.0 on testnet. For me strange, testnet has less activity and nodes than mainnet, but CPU usage higher. And also if I downgrade to 2.4 on testnet - load falls.

May be do profiling somehow... right now I see CPU load same 50%, and mainnet 2.4 0%
There one diffrent in java version 8 and 13, may be try to launch 3.0 on 8?

**Comment by llybin** [comment]
May be you run pre-verification on each request from others nodes? For example, every node do broadcast block, and 3.0 pre-verificate each one, but they are same. I not looked into code yet, sorry. I sure current cpu usage is not normal and was better in this case. Of course, increasing speed sync cool, but why CPU used when no new blocks?

**Comment by harry1453** [comment]
That's strange, I'll look into it. Also, I develop against Java 8

**Comment by harry1453** [comment]
cb5d5dfb8808efbb207185b4312a5b9567ff8dcf Should fix the issue...

**Comment by llybin** [comment]
Quick test shown much better, thank you! I will test more after fix this issue: https://github.com/burst-apps-team/burstcoin/issues/326

**Comment by llybin** [comment]
looks good now
