### ISSUE TITLE
Use localization management platform

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#299]
For example I use this one: https://poeditor.com/ Free for open source. There have another services.

**Comment by harry1453** [comment]
You mean for the frontend?

**Comment by llybin** [comment]
Yes, if translations only on front-end. But if in plan get rid this front-end or planning less changes may be don't need it

**Comment by harry1453** [comment]
It would be a good idea to suggest this for Phoenix

**Comment by llybin** [comment]
Already, they are have something https://github.com/burst-apps-team/phoenix/issues/1112 for me diffrent things.
