### ISSUE TITLE
brs.db.sql.SqlDb - WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#306]
[INFO] 2020-01-04 17:11:19 brs.db.sql.SqlDb - Running flyway migration
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jooq.tools.reflect.Reflect (file:/app/burst.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class)
WARNING: Please consider reporting this to the maintainers of org.jooq.tools.reflect.Reflect
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**********
SYSTEM INFORMATION
RT: OpenJDK Runtime Environment, Version: 13-ea+32
VM: OpenJDK 64-Bit Server VM, Version: 13-ea+32
OS: Linux, Version: 4.15.0-72-generic, Architecture: amd64
**********

BRS v3.0.0-alpha4

**Comment by llybin** [comment]
Sorry, just now saw it's from package org.jooq.tools.reflect.Reflect

**Comment by harry1453** [comment]
Yep. This cannot be fixed in jOOQ without dropping Java 8 support so we'll have to put up with the warning, which is harmless.
