### ISSUE TITLE
brs-testnet.properties actual public peers

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#307]
Update BootstrapPeers and rebroadcastTo in brs-testnet.properties

52.65.42.199; 75.100.126.230; aya.onthewifi.com; fitzybits.mynetgear.com; test-burst.megash.it; wallet.testnet.burst.devtrue.net; testnet.getburst.net; tordek.mine.nu

**Comment by llybin** [comment]
Harry, just take it in next brs-testnet.properties It actual public testnet peers, and close task :)

**Comment by harry1453** [comment]
I have updated my copy that I use when making testnet releases, we do not have a copy checked in

**Comment by llybin** [comment]
https://github.com/burst-apps-team/burstcoin/pull/345 let's discuss this one, there I suggest add it, any comments are appreciated, let's do what we all will like(exclude shitcoders)(joke)

**Comment by jjos2372** [comment]
There is a new list of testnet peers already.
