### ISSUE TITLE
When solo mining you don't see your forget blocks at Dashboard.

### ISSUE THREAD

**Issue by shefass** [burst-apps-team/burstcoin#31]
When solo mining you don't see your forget blocks at Dashboard, Recent Transactions. You only can see it at the Blocks section. I think it was better user experience to put info about forget block at Dashboard to Recent Transaction. Sure it is not important issue, because solo mining not popular.

**Comment by jjos2372** [comment]
@shefass please check if this is still an issue for the upcoming next release. If not, please close it.

**Comment by jjos2372** [comment]
No good space to add this on the dashboard, we are now showing the committed value which is more useful for miners.
![image](https://user-images.githubusercontent.com/31958515/113361024-5f7a8180-9321-11eb-98a0-6ba796676b85.png)
