### ISSUE TITLE
2 problems with subscription fee

### ISSUE THREAD

**Issue by zodi1337** [burst-apps-team/burstcoin#32]
I guess i found 2 problems / proposals in the burst wallet, concerning the subscription fee's.

1.
If you create a subscription, in my opinion there should be the same "suggested fee" button/line like if you do a normal transaction with "send burst"
![image](https://user-images.githubusercontent.com/35403144/51193373-031a1b80-18e9-11e9-9d8b-b701f9e83a32.png)
![image](https://user-images.githubusercontent.com/35403144/51193428-1f1dbd00-18e9-11e9-8524-02d29b6d1a8e.png)

2.
If you create a subscription (with low fee, in my case 0.01 burst) it's working, but all subscription after creating it will have a fee of 1 burst. Is it possible to do this also with low fees, or will it open an attack surface?
If it should be no problem to let the subscriptions work with low fee, i suggest two fee options, one for the "creating subscription transaction" and one for the "subscriptions itself".

Bit sadly i did my test on the mainnet, since we got a brand new testnet now! ;) ty for this

I did my test with the burst id's:
BURST-N3AP-DXZN-YMFP-AFACQ and BURST-HZ3D-4S5X-2ALC-95TR2

![image](https://user-images.githubusercontent.com/35403144/51194022-7e300180-18ea-11e9-8d00-3dc502d091d0.png)

**Comment by harry1453** [comment]
https://github.com/burst-apps-team/burstcoin/blob/1cce774db3613474f6db5414495a0a5e67c1d9fc/src/brs/services/impl/SubscriptionServiceImpl.java#L92

We need to see if this change will require a fork... It depends how the node verifies these types of transactions

**Comment by frankTheTank72** [comment]
As i see it will come with the next hard-fork ; can @harry1453 explain which fee will be used for the subscription payments ? As this payments computed beside the normal tx ; can we use the min-fee of 0,00735 pls … thx

**Comment by shefass** [comment]
"... computed beside the normal tx" If it is will be (or are) based on
normal transactions, we must consider our slot system. The first slot
(0.00735) will be taken always or nearly always if people will start to use
Burst more.

2019-10-13, sk, 23:08 frankTheTank72 <notifications@github.com> rašė:

**Comment by frankTheTank72** [comment]
Can we please add this to the next hard-fork items aka BRS 3.0.0. We should reduce the ongoing fee for the subscription to lowest 0,00735 BURST. @ohager may you take this up inside the BAT team pls

**Comment by ohager** [comment]
@harry1453 Wdyt? Did you make any analysis regarding impacts on lowering subscription fee?

**Comment by harry1453** [comment]
I didn't, it wouldn't really make much of a difference I don't think, the question is how a subscription fee is selected.

**Comment by ohager** [comment]
There should be no selection at all... let it fixed like it does done today, just lower the constant. KISS

**Comment by harry1453** [comment]
That's one option, but this feels like an opportunity to implement some kind of smarter method

**Comment by ohager** [comment]
Use the suggestFee implementation and always select the standard fee. Smart enough?

**Comment by shefass** [comment]
I forgot this issue, I am 99% sure that subscription payments bypass slot
system and do it inside node (you no need to do actual propagation of
transaction, because logic is inside node(node already know how to act) )
so it can be changed to QuantumFee. Now it is hardcoded to  Burst.ONE

2020-03-15, sk, 21:35 ohager <notifications@github.com> rašė:

**Comment by frankTheTank72** [comment]
I would keep it simple for the subscriptions and just move from 1 BURST to MIN-FEE aka 0.00735 BURST.  So ppl can also plan the ongoing cost with the subscription over time.

**Comment by harry1453** [comment]
I like the idea of using fee quant, it's more predictable.

**Comment by frankTheTank72** [comment]
yes @harry1453  FEE_QUANT would be perfect

**Comment by jjos2372** [comment]
Fees for subscriptions were already reduced on the SODIUM HF.
