### ISSUE TITLE
3.0.0-dev API getInfo return incorrect announcedAddress

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#326]
The last version on current moment return incorrect announcedAddress in request to API getInfo

curl -X POST "http://wallet.testnet.burst.devtrue.net:7123/burst" -H "User-Agent: BRS/2.3.0" -d '{"protocol": "B1", "requestType": "getInfo"}' 

{"application":"BRS","version":"v3.0.0-dev","platform":"DEVTRUE DS DOCKER","shareAddress":true,"announcedAddress":"grpc://wallet.testnet.burst.devtrue.net:7120"}

**Comment by llybin** [comment]
or maybe this expected behavior? It breaks explorer, want to understand what changes needed.

**Comment by harry1453** [comment]
this is expected behaviour for a new node, but it should detect that you are a BRS 2.3 node and give you an old-style address...

The new address format is `(grpc|http)://[address]:[port]`, and port is always included

**Comment by harry1453** [comment]
Actually, this is the **announced** address, which is not supposed to be backwards compatible... An old peer *should* either handle or ignore it...

**Comment by llybin** [comment]
So, close?

**Comment by harry1453** [comment]
Yep
