### ISSUE TITLE
testnet brs 3.0.0-alpha5 incorrect peers

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#346]
1. currently testnet fully stuck 4 days ago, I've checked some nodes from here https://github.com/burst-apps-team/burstcoin/issues/307 they are all: 141044 4 days, 5 hours ago
2. https://wallet.testnet.burst.devtrue.net upgraded to alpha5. Three entities of one my node. first two are internal docker IPs.

![image](https://user-images.githubusercontent.com/5445357/75180163-324abf80-576e-11ea-927d-d27bbc3cadba.png)

my conf:

```
P2P.myAddress = wallet.testnet.burst.devtrue.net
P2P.myPlatform = DEVTRUE DS DOCKER
P2P.UPnP = no
P2P.savePeers = true
P2P.usePeersDb = true
P2P.getMorePeers = true
P2P.shareMyAddress = true
CPU.NumCores = 1
PreVerifier.NumberOfInstances = 1

API.Listen = 0.0.0.0
API.allowed = *

DEV.API.Port = 6876
DEV.P2P.V2.Port = 7120
DEV.API.V2.Port = 6878

DEV.DB.Url = jdbc:mariadb://<<>>:3306/<<>>
DEV.DB.Username = <<>>
DEV.DB.Password = <<>>

DEV.TestNet = yes
DEV.Offline = no

DEV.P2P.BootstrapPeers = 52.65.42.199; 75.100.126.230; aya.onthewifi.com; fitzybits.mynetgear.com; test-burst.megash.it; testnet.getburst.net; tordek.mine.nu
DEV.P2P.rebroadcastTo = 52.65.42.199; 75.100.126.230; aya.onthewifi.com; fitzybits.mynetgear.com; test-burst.megash.it; testnet.getburst.net; tordek.mine.nu

DEV.digitalGoodsStore.startBlock = 0
DEV.automatedTransactions.startBlock = 0
DEV.atFixBlock2.startBlock = 0
DEV.atFixBlock3.startBlock = 0
DEV.atFixBlock4.startBlock = 0
DEV.preDymaxion.startBlock = 0
DEV.poc2.startBlock = 0
DEV.rewardRecipient.startBlock = 6500
```

**Comment by llybin** [comment]
1. no miners on testnet ) https://explorer.testnet.burst.devtrue.net/block/141045

**Comment by harry1453** [comment]
That is very strange... It's picking itself up twice. Will look into this

http://75.100.126.230:8124/index.html should still be mining

**Comment by harry1453** [comment]
Oops looks like the pool got stuck, will reboot it

**Comment by jjos2372** [comment]
This branch is not under development at the moment.
