### ISSUE TITLE
testnet Transaction is not included in block for a long time

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#347]
If I right understand slots, they should accept my transaction?

![image](https://user-images.githubusercontent.com/5445357/75252532-780b9480-580f-11ea-883a-a03b8b815ded.png)

How to reproduce: 
send message to any wallet with 0.1 fee
"Subscription Payment" transaction on each block accepted, but mine no

![image](https://user-images.githubusercontent.com/5445357/75252810-f9fbbd80-580f-11ea-8218-a112eedd8ad2.png)

![image](https://user-images.githubusercontent.com/5445357/75253202-a89ffe00-5810-11ea-9519-3f5e603a7fcc.png)

![image](https://user-images.githubusercontent.com/5445357/75253470-28c66380-5811-11ea-830e-ec0d58f9a67c.png)

Any idea? wallet Ruby miner doesn't see my transactions?

I started dig it after that: https://explorer.testnet.burst.devtrue.net/txs/?block=141103
When ohager sent transaction mine were accepted too, but I can't reproduce it, but my transactions still are not accepting

**Comment by llybin** [comment]
I sent above from http://wallet.testnet.burst.devtrue.net/ 3.0.0-alpha5

Next, I sent transaction from http://testnet.getburst.net:6876 (currently v2.4.0-beta2)

after some second I started to see this unconfirmed transaction on http://wallet.testnet.burst.devtrue.net/ , and in next block my all transactions was accepted. Looks like reproduced, some bug with unconfirmed sync.

**Comment by harry1453** [comment]
Could be unconfirmed sync not working on new P2P

**Comment by jjos2372** [comment]
Old 3.0 branch no longer in development.
