### ISSUE TITLE
Bottleneck in sync speed

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#350]
Version: https://github.com/burst-apps-team/burstcoin/commit/6a5c7d9d8706eb3dd0a4a6792820b3c8c344999f

In attached screencast you can see  CPU is not utilized fully: https://yadi.sk/i/SSJRwI8N0dXyqQ

Reproduced.

**Comment by harry1453** [comment]
Most of the bottleneck now is waiting for sync locks or waiting for the DB to do something... Not sure if there's a whole lot we can do for now

**Comment by llybin** [comment]
I keep digging, the bottleneck is queries by accounts.

**Comment by harry1453** [comment]
that shouldn't be too slow, accounts should be cached...

**Comment by llybin** [comment]
if that not "shefas" transactions, if you understand what I mean :D
these accounts usually never used even twice, always only new accounts, so, 149*128 select , and after 149*128 updates and inserts , on a block. 19272 * 3 = 57816 queries on block :)

https://explorer.testnet.burst.devtrue.net/txs/?block=4448

**Comment by llybin** [comment]
[INFO] 2020-03-02 14:16:54 brs.services.impl.StatisticsServiceImpl - handling 3.05 blocks/s  account cache hit ratio now/total:26.16%/26.86%

**Comment by harry1453** [comment]
Yep that's due to the multi-out spam that starts at block 4447.

The main slowdown is adding new accounts to the accounts table (149 transactions * 128 recipients = 19072‬ new accounts per block) and the indirect incoming entries that go along with that (another 19k)

**Comment by llybin** [comment]
Harry, could you help implement extending of cache. I would like to know state of record, exists in database (need update) or it's new record - need insert. Currently only entity stores in cache, I want store  state of entity, if you will implement me a base functional - I'll can next. It should be a huge speed increase after that task.

![image](https://user-images.githubusercontent.com/5445357/75879296-bcb9b000-5e4d-11ea-9a4b-5b6778ecb8d3.png)

**Comment by llybin** [comment]
Harry, how I can get account.db_id from entity? I want to know what operation to do, insert or update, if db_id is not null - a record in DB.

![image](https://user-images.githubusercontent.com/5445357/75882168-33a57780-5e53-11ea-8807-3d12020315cf.png)

Another idea extend cache to store it

![image](https://user-images.githubusercontent.com/5445357/75882354-91d25a80-5e53-11ea-86e4-a8140b045b82.png)

What you think, how can better implement it?

**Comment by harry1453** [comment]
The current design is that there is no coupling or even awareness between the DB and the entities. The cache is designed around this principle too: The rest of the program is unaware that caching exists, it's part of the DB implementation. So, I'm hesitant to do this unless we either:

* Change the way the program is designed, so that there is coupling between entities and DB

* Make it so that this is implemented in a subclass, such as `SQLAccount` (IIRC there used to be a subclass like this but it wasn't used for this)

I don't see why the insert / update issue is critical because the DB natively handles the upsert, it's not done in BRS.

**Comment by llybin** [comment]
> I don't see why the insert / update issue is critical because the DB natively handles the upsert, it's not done in BRS.

The same reason why/what I did in prev PRs.

Upsert is ONE query, he can contain only ONE record. So, if block contain 149 * 128 transactions - it's 149 * 128 upsert queries on accounts in row. If we will know which records need update, which - insert we can group that in two query, one update and one insert - will only two query instead 149 * 128, it will much faster. P.S. I said only two queries for more clear undestanding, in real will maximum 20, same as in prev PR with chunck.

Next, before upsert we do update latest=0 (the prev PR), also this update contain new accounts(not yet in DB). At this step we also don't know which records don't need update with latest=0, because they even don't exists, that can reduce the update queries in prev PR also.

Next, the biggest bottleneck is 149 * 128 selects in a row, how it's solve I prefer talk later after optimization insert/update.

We can to know what to do, update or insert, but we prefer currently do upsert, upsert for database also more comlicated operation than only insert or update. But it's minor with comparing possible optimization of amount of that queries.

**Comment by harry1453** [comment]
Okay. In that case it seems like we need to optimize how we're doing the upsert. And my problem is that I'm not convinced that doing selects to find what we need to insert and what we need to update will be faster than the database's upsert functionality, even if we cache, because the DB can do that with internal caching or with less network overhead.

**Comment by harry1453** [comment]
Upsert is used so commonly that I think it would be significant work to start maintaining a cache of whether a record exists for every type of entity..

**Comment by llybin** [comment]
Sorry, you didn't say about count of queries, so I repeat, suddenly we have no understanding. Important to decrease count of queries to DB, not get rid UPSERT. Getting rid of UPSERT is only a side effect. But, yesI preffer more explicit insert/update than upsert when it possible.

For example we have two records, we don't know they exist or not in DB. We do two UPSET queries. We can't group/collapse these two queries to one query, because UPSERT operation doesn't support that. If we have 100 records - we must to do 100 UPSERT queries and etc. (at the moment it is)

If we know what to do for each record insert or update. We can group these queries only in two queries, one insert with multi values and one update with multi values. Same as I did in prev PRs.

Right now, I found in google that I was wrong about UPSERT doesn't support multiple values. https://stackoverflow.com/questions/20255138/sql-update-multiple-records-in-one-query/20255203
So easiest way implement like that, need to test, https://stackoverflow.com/a/42742362

I'll try, I believe it's not maximum optimization but we should see speed increasing.

See, for example each query takes 10ms +/- for example, but when we have 19072 queries:

19072 * 10ms / 1000 / 60 = ~3min ! So what we can see if enable logging DEBUG, CPU utilization near zero and first, 19072 select queries in a row, next update latest=0 (optimized in prev PR, max 20 queries), next, 19072 upsert queries.

If cache can store existance of record, we can create "bulk select" in one query, preload using one select: select id, ... from accounts where id in (....) next, prepopullate cache even with empty records, and when select query will in loop, record cached already, we can see by existance in cache, and don't do real query to DB.
The rest of the program is unaware that caching exists, and it will same. Currently we store key_id: values. We can store in cache: key_id: (values, existance in DB) We will return only values for the rest app, existance only for cache logic.

**Comment by harry1453** [comment]
Please let me finish #375 before you start working as I have unpushed changes

**Comment by llybin** [comment]
yep, I see and waiting your PR, but if get rid upsert, your problem will leave ;)

**Comment by harry1453** [comment]
Problem is we can't get rid of upsert for now. The way to get rid of upsert is to turn every single entity table into a batch entity table, which I am working on :)

**Comment by ohager** [comment]
@jjos2372 still an issue? I tend to close this.

**Comment by jjos2372** [comment]
This was for the previous kotlin based version, closing for now.
