### ISSUE TITLE
Transaction 428526048786081451 is a theft?

### ISSUE THREAD

**Issue by onlyjob** [burst-apps-team/burstcoin#351]
I have not been using Burst wallet in a while (last version I've used was 2.2.1 or 2.2.2 when it was still current in the mid 2018).
Now I have installed v2.4.2, re-downloaded blockchain and found a [recent](https://explore.burst.cryptoguru.org/transaction/428526048786081451) [transaction](https://explorer.burstcoin.network/?action=transaction&id=428526048786081451) transferring all my BURST to `BURST-YEF5-4XJE-8LQK-DQ52K`. That's a theft, right?
Any ideas of how this is done? I'm guessing brute force attack on the wallet?

Thanks.

**Comment by shefass** [comment]
"I'm guessing brute force attack on the wallet?" If you was using default
12 words password (I think from 6 words..), brute force not passable.So if
your password was "my super good password" it is passable.
But more realistic variant that you was using some online service and give
away you password.

2020-03-01, sk, 00:22 Dmitry Smirnov <notifications@github.com> rašė:

**Comment by onlyjob** [comment]
I have never used any online services (let alone exposed password online), never wrote down my password, only ever used locally installed wallet on local GNU+Linux workstation.
Though password was arguably weak (12 characters long passphrase)...

**Comment by shefass** [comment]
So answer brute force, specially if you was using word from dictionary
or no special characters.

2020-03-01, sk, 00:40 Dmitry Smirnov <notifications@github.com> rašė:

**Comment by onlyjob** [comment]
Thanks, @shefass.
