### ISSUE TITLE
Review foreignkeys in all migrations

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burstcoin#353]
1. sqlite fully doesn't contains foreignkeys
2. mariadb (maybe h2 also) doesn't contains foreignkeys  in most tables on: sender_id, recipient_id, account_id, asset_id, creator_id, at_id, escrow_id, seller_id, buyer_id, goods_id, prev_recip_id, recip_id, block_id, ask_order_id, bid_order_id, ec_block_id

**Comment by harry1453** [comment]
this is likely historical... when I transitioned over to using flyway to handle migrations I just compiled the previous migration scripts into one script

**Comment by llybin** [comment]
How can to add it? Just create new file sql migration?

**Comment by harry1453** [comment]
Yep, you can't modify existing migrations but you can add a V4, for instance

**Comment by llybin** [comment]
ok I'll take this task. I asked because maybe need modify models, ok thx I understood

**Comment by llybin** [comment]
Can I create for sqlite from scratch migration? sqlite doen't allow modify schema, it will looks like:

``` sql
create table account_asset_dg_tmp
(
	db_id INTEGER
		primary key autoincrement,
	account_id BIGINT not null
		constraint account_asset_account_id_fk
			references account (id)
				on delete cascade,
	asset_id BIGINT not null,
	quantity BIGINT not null,
	unconfirmed_quantity BIGINT not null,
	height INT not null,
	latest BOOLEAN default TRUE not null
);

insert into account_asset_dg_tmp(db_id, account_id, asset_id, quantity, unconfirmed_quantity, height, latest) select db_id, account_id, asset_id, quantity, unconfirmed_quantity, height, latest from account_asset;

drop table account_asset;

alter table account_asset_dg_tmp rename to account_asset;

create unique index account_asset_id_height_idx
	on account_asset (account_id asc, asset_id asc, height desc);

create index account_asset_quantity_idx
	on account_asset (quantity desc);


```

**Comment by llybin** [comment]
I can't add foregin key to h2 db:

``` sql

BURST.H2.PUBLIC> alter table "account_asset"
                     add constraint ACCOUNT_ASSET_ACCOUNT_ID_FK
                         foreign key ("account_id") references "account" ("id")
                             on delete cascade
[2020-03-06 02:31:34] [23505][23505] Unique index or primary key violation: "PUBLIC.ACCOUNT_ASSET_ACCOUNT_ID_FK_INDEX_B ON PUBLIC.account(id) VALUES 461385"; SQL statement:
[2020-03-06 02:31:34] alter table "account_asset"
[2020-03-06 02:31:34] add constraint ACCOUNT_ASSET_ACCOUNT_ID_FK
[2020-03-06 02:31:34] foreign key ("account_id") references "account" ("id")
[2020-03-06 02:31:34] on delete cascade [23505-200]
```

I not found solution: https://www.google.com/search?q=h2+alter+table+add+constraint+foreign+key+Unique+index+or+primary+key+violation

probably bug in h2, data is consistent, I've checked.

any idea and what will to do?

**Comment by harry1453** [comment]
As we haven't released SQLite to mainnet, yes. MariaDB and H2 old migrations cannot be changed
