### ISSUE TITLE
Check for internet connectivity when mining

### ISSUE THREAD

**Issue by harry1453** [burst-apps-team/burstcoin#388]
If a miner loses their internet connection and forges a block, they start building their own private chain and BRS may not resolve the fork if the internet outage is too long or it decides their fork is preferable

**Comment by jjos2372** [comment]
This was partially fixed. There was a bug preventing a node to reconnect after losing all peers. The problem will still persist if the node keeps mining offline for more than 1440 blocks, but that is less of a problem.
