### ISSUE TITLE
BRS V3 - Remove predefined domain names in Deeplink Generator

### ISSUE THREAD

**Issue by ohager** [burst-apps-team/burstcoin#421]
Currently, the BRS V3 implementation in CIP22 foresees predefined domain names. This way, app developers lack the flexibility they need to link different applications...BRS 2.5 has variable domain names already.

**Comment by frankTheTank72** [comment]
still needed ?

**Comment by jjos2372** [comment]
@ohager please take a look and close if not necessary.

**Comment by ohager** [comment]
CLosing, as Kotlin Version (prior V3) is not being continued
