### ISSUE TITLE
HTTP Error 405 when trying to access web interface

### ISSUE THREAD

**Issue by benthetechguy** [burst-apps-team/burstcoin#438]
I just installed BRS on an ubuntu machine. I have not changed the configuration from default. Whenever I try to access the web interface, I get an HTTP error 405. It says "HTTP method GET is not supported by this URL." Does anybody know why this is happening and how to fix it?

**Comment by jjos2372** [comment]
Is BRS running on the same machine you are trying to access the web interface? If not, you probably need to check your configuration file to enable remote access.

**Comment by benthetechguy** [comment]
Oh, I didn't realize I had to change it to enable remote access. What would I change in the config to enable that?

**Comment by jjos2372** [comment]
Read the comments on the config file, look for options like:
 - API.allowed
 - API.Listen

**Comment by benthetechguy** [comment]
I changed everything I could see in the config related to remote access, and it didn't change anything. As this issue is closed and I can't reopen it, I have moved it to issue #440.

**Comment by shefass** [comment]
"HTTP method GET is not supported by this URL."

My guess is that you are trying to call POST only api calls with GET
method. Try changing GET to POST

2020-06-16, an, 18:12 benthetechguy <notifications@github.com> rašė:

**Comment by benthetechguy** [comment]
How would I do so? All I'm doing is typing http://<IP address>:8123 in chrome

**Comment by shefass** [comment]
You mean http://localhost:8125 ? and you get this error in your browser?

2020-06-16, an, 19:20 benthetechguy <notifications@github.com> rašė:

**Comment by jjos2372** [comment]
Sorry for closing it before, I assumed it would be an easy fix on your side. I'll reopen until you confirm it is solved. Yes, as @shefass said, the port for the wallet is **8125**.

**Comment by benthetechguy** [comment]
I have fixed the issue by realizing my obvious mistake of using the wrong port. Thanks for being nice and trying to help me in the normal ways though!

**Comment by shefass** [comment]
np. I always make these simple mistakes:) Missing later and etc..

2020-06-17, tr, 03:38 benthetechguy <notifications@github.com> rašė:
