### ISSUE TITLE
HTTP Error 405 when trying to access web interface

### ISSUE THREAD

**Issue by benthetechguy** [burst-apps-team/burstcoin#440]
This issue is in reference to issue #438 where I was having the issue, and @jjos2372 closed it before I could say the solution didn't work. I enabled everything I could see in the config for remote access, and it still doesn't work. I am attaching my config below.
[brs.properties.txt](https://github.com/burst-apps-team/burstcoin/files/4787358/brs.properties.txt) (btw the config is in a .txt file because github doesn't support .properties files to be attached)

**Comment by benthetechguy** [comment]
btw the config is in a .txt file because github doesn't support .properties files to be attached

**Comment by jjos2372** [comment]
Please describe in detail how you are trying to access the remote wallet.

**Comment by jjos2372** [comment]
If you have:
```
API.allowed = 0.0.0.0; localhost; [0:0:0:0:0:0:0:1];
API.Listen = 0.0.0.0
```
You should be able to access from a remote server on http://ip-of-your-server:8125

(sorry for closing the other one, once solved we close both)

**Comment by benthetechguy** [comment]
Oh, I was using port 8123. I didn't realize that was for P2P instead of http. Derp! Thanks for helping during my period of idiocy.
