### ISSUE TITLE
Missing Multi-Out transactions when calling getAccountTransactions

### ISSUE THREAD

**Issue by andzno1** [burst-apps-team/burstcoin#447]
I am using Burst Reference Software version v2.5.1

## Expected Behavior
All Multi-Out transactions (`MultiSameOutCreation` and `MultiOutCreation`) should be included in the result when calling `getAccountTransactions` with the `includeIndirect` parameter set to `true`.

## Actual Behavior

When calling `getAccountTransactions` on a fully synchronized local wallet with the `includeIndirect` parameter set to `true`, not all Multi-Out transactions are being included in the result. 

E.g. when calling
```shell
curl "http://localhost:8125/burst?requestType=getAccountTransactions&account=BURST-GT5F-6VQD-CLM6-6Q5BX&includeIndirect=true" | jq -r '(.transactions) | sort_by(.timestamp)'
```

the oldest `MultiSameOutCreation` entry in the result belongs to transaction `5536828545919970201` (2019-09-01), but the oldest `MultiSameOutCreation` transaction on that account is `10065574561891767476` (2019-03-10) as you can see on the screenshot:

![image](https://user-images.githubusercontent.com/4320938/90990598-06848700-e5a3-11ea-9d54-b83ba21a82dd.png)

Same goes with `MultiOutCreation`. The oldest in the curl result belongs to transaction `2943760754662497727` (2019-09-21), but the oldest `MultiOutCreation` transaction on the account is `3578439527840352455` (2018-07-06):

![image](https://user-images.githubusercontent.com/4320938/90990644-4f3c4000-e5a3-11ea-8095-a587abc9ddb9.png)

**Comment by jjos2372** [comment]
I haven't checked this, but there is a limit of 500 items on any API call, isn't this the source of your issue? You can use the `firstIndex` and `lastIndes` to paginate the results.

**Comment by andzno1** [comment]
Thanks for pointing that out. Is there an official API documentation for this version of the BRS?

Unfortunately the API call yields only 441 transactions:
```shell
curl -s "http://localhost:8125/burst?requestType=getAccountTransactions&account=BURST-GT5F-6VQD-CLM6-6Q5BX&includeIndirect=true" | jq -r '(.transactions) | length'
441
```

**Comment by jjos2372** [comment]
Every node has the entire API and parameters available at `/test`, check for instance: https://wallet.burst-alliance.org:8125/test

Maybe the limit of 500 items goes before some other filtering, it is probably safer for you to paginate and check if you get all transactions.

**Comment by andzno1** [comment]
I was just playing around with pagination. Can you explain me this behavior?
```Shell
curl -s "http://localhost:8125/burst?requestType=getAccountTransactions&account=BURST-GT5F-6VQD-CLM6-6Q5BX&firstIndex=60&lastIndex=500&includeIndirect=true" | jq -r '(.transactions) | length' 
326

curl -s "http://localhost:8125/burst?requestType=getAccountTransactions&account=BURST-GT5F-6VQD-CLM6-6Q5BX&firstIndex=50&lastIndex=500&includeIndirect=true" | jq -r '(.transactions) | length'
341
```

Lowering `firstIndex` by 10 yields 15 more transactions.

Calling
```Shell
curl -s "http://localhost:8125/burst?requestType=getAccountTransactions&account=5666784140691203181&firstIndex=300&lastIndex=399&includeIndirect=true" | jq -r '(.transactions) | length'        
86
```
returns 86 transactions. I would have expected 100, since there are at least 441 transactions for that account. I am very confused.

**Comment by andzno1** [comment]
When I call
```Shell
curl "http://localhost:8125/burst?requestType=getAccountTransactions&account=BURST-GT5F-6VQD-CLM6-6Q5BX&firstIndex=385&lastIndex=385&includeIndirect=true"
```
I get one transaction, when I call 
```Shell
curl "http://localhost:8125/burst?requestType=getAccountTransactions&account=BURST-GT5F-6VQD-CLM6-6Q5BX&firstIndex=386&lastIndex=386&includeIndirect=true"
```
I get none. 386 seems to be the Number of ordinary transactions for this account:
![image](https://user-images.githubusercontent.com/4320938/91091172-815aaa00-e656-11ea-9ad7-3e4aae241b8d.png)

Is it possible, that pagination breaks the purpose of the `includeIndirect` parameter?

**Comment by andzno1** [comment]
Do you need some more information?

**Comment by jjos2372** [comment]
The `includeIndirect` ends up appending the indirect transactions over the *regular* ones. One would need to review its logic to say exactly what is going on.

**Comment by jjos2372** [comment]
Hi @andzno1 have you investigated this a bit more? I'm planning to address this issue and if you have any other information before I start, it could be helpful.

**Comment by jjos2372** [comment]
It looks like the source of the problem is here:
https://github.com/burst-apps-team/burstcoin/blob/b8550caa3bd4da528f611f1effd3c92dc3227a30/src/brs/db/sql/SqlBlockchainStore.java#L161

With the pagination limits being applied twice, first there and again on here:
https://github.com/burst-apps-team/burstcoin/blob/b8550caa3bd4da528f611f1effd3c92dc3227a30/src/brs/db/sql/SqlBlockchainStore.java#L168

By removing the limits on the first line above it should fix the problem.

**Comment by jjos2372** [comment]
Fixed, will be on the next release.
