### ISSUE TITLE
2.5.3 Running out of heap memory when doing the new database check

### ISSUE THREAD

**Issue by octalsipika** [burst-apps-team/burstcoin#451]
Updated my pi3 to 2.5.3 and get the following error

```
Oct 06 17:49:17 BURSTNODE java[27198]: [INFO] 2020-10-06 17:49:17 brs.BlockchainProcessorImpl - Checking database state (it can take a minute or two)...
Oct 06 17:50:51 BURSTNODE java[27198]: Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
```

I flashed ubuntu 64 bit on it to try and 64bit java but still the same issue.

**Comment by jjos2372** [comment]
We probably need another logic for the DB consistency check for low memory machines. For now, you can skip the DB check with the following option:
`DB.SkipCheck = true`
