### ISSUE TITLE
BRS V3 issue

### ISSUE THREAD

**Issue by shaneo257** [burst-apps-team/burstcoin#462]
You bunch of idiots, you can't develop an application for the life of yas, give up on burst because your all useless and let the coin do what its supposed to do, and die

![image](https://user-images.githubusercontent.com/36589806/108819724-eb084080-7606-11eb-8e5b-b328378136b1.png)

**Comment by shefass** [comment]
Lol:) We have fan on GitHub! Welcome.
I hope you feel better.

2021-02-23, an, 10:43 shaneo257 <notifications@github.com> rašė:

**Comment by shaneo257** [comment]
yeh a fan of the project finally getting buried where it belongs

**Comment by shefass** [comment]
Why you like this project?

2021-02-23, an, 10:50 shaneo257 <notifications@github.com> rašė:

**Comment by shaneo257** [comment]
I don’t

It’s run by scammers and spammers that is worse than pocc

**Comment by shefass** [comment]
So you are not a fan of project?

2021-02-23, an, 10:58 shaneo257 <notifications@github.com> rašė:

**Comment by shaneo257** [comment]
Nobody is a fan

its a dead coin on life support

**Comment by shefass** [comment]
You are the best fan! You are interested in the coin and want to bury it.
It is very nice that you care and say your opinion. Thank you.

2021-02-23, an, 11:01 shaneo257 <notifications@github.com> rašė:
