### ISSUE TITLE
Marketplace: Quantity Of Products For Sale: Can't Amend more than once. Testnet

### ISSUE THREAD

**Issue by AussieDelly** [burst-apps-team/burstcoin#48]
![screen shot 2019-02-09 at 2 37 35 pm](https://user-images.githubusercontent.com/18495134/52516035-5d07ca00-2c78-11e9-960f-e3c5b63971de.png)

I can amend the quantity once. But the SECOND time nothing happens.
No update is applied when submitted by the Wallet UI or API directly
No error is returned when the request is sent. 

However, the quantity available to be sold is updated correctly when purchases are made.

**Comment by harry1453** [comment]
If this is a proper breakage in BRS this has the potential to be a hard fork fix.

**Comment by AussieDelly** [comment]
@harry1453 Is anyone actively looking at this?  I'm playing around with an insurance project. Reducing the quantity of the product, in my case the amount of cover available in Burst, allows me to enforce an Embargo.  Maybe a bad storm is forecast to hit a region and I don't want to sell insurance. Later I want to amend the quantity back up again after the storm has passed.

I don't really understand why this is a hard fork when as the quantity changes just fine on a normal purchase.

I'll try and find the issue myself if no one is actively looking at it.  Please let me know.

**Comment by harry1453** [comment]
Can you provide steps to reproduce?

**Comment by harry1453** [comment]
I'm completely unable to reproduce on v2.4.0-beta2. Can you verify that this issue has persisted since 2.3.0? I have a feeling that this got fixed at the same time as the reward recipient bug as the symptoms are similar

**Comment by AussieDelly** [comment]
I hope you're right. I'll try on the testnet now. Thanks

**Comment by AussieDelly** [comment]
@harry1453 Good News it works again on the TestNet!  
Thanks for reponding to my query so quickly.

![Screen Shot 2019-05-24 at 9 08 17 pm](https://user-images.githubusercontent.com/18495134/58323846-808e0380-7e68-11e9-8ffc-9df91bbea36c.png)

![Screen Shot 2019-05-24 at 9 02 16 pm](https://user-images.githubusercontent.com/18495134/58323782-59cfcd00-7e68-11e9-8b0f-ba48ab55e9bb.png)

![Screen Shot 2019-05-24 at 9 05 32 pm](https://user-images.githubusercontent.com/18495134/58323813-6d7b3380-7e68-11e9-9e71-e47ee60def54.png)

![Screen Shot 2019-05-24 at 9 11 41 pm](https://user-images.githubusercontent.com/18495134/58323881-9b607800-7e68-11e9-86b5-f1c4f8fe2669.png)
![Screen Shot 2019-05-24 at 9 14 41 pm](https://user-images.githubusercontent.com/18495134/58323900-ae734800-7e68-11e9-9889-980fac0a5b5b.png)

![Screen Shot 2019-05-24 at 9 19 43 pm](https://user-images.githubusercontent.com/18495134/58324002-f2fee380-7e68-11e9-98fe-debaa6686436.png)

I'm happy for this issue to be closed if you are.

**Comment by harry1453** [comment]
Glad it's sorted.
