### ISSUE TITLE
Upgrading to 3.0.0 from 2.5.4 fails

### ISSUE THREAD

**Issue by Kafkamorph** [burst-apps-team/burstcoin#483]
`Caused by: org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected failed migration to version 3 (indirect incoming index). Please remove any half-completed changes then run repair to fix the schema history.
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:173)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
        at org.flywaydb.core.Flyway.execute(Flyway.java:570)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
        at brs.db.sql.Db.init(Db.java:140)
        ... 3 more
[INFO] 2021-04-08 10:13:51 brs.Burst - Shutting down...`

**Comment by jjos2372** [comment]
This is the first report of this kind. Many have successfully upgraded 2.5.4 using both MariaDB as well as H2 as backend. Over 25% of the network has already upgraded in this first day. I'll keep this open for now, but it looks like something particular to your setup. Perhaps, an unclean shutdown before the upgrade. I advise you to make a sync from empty.

**Comment by Kafkamorph** [comment]
Thanks for that info.
I have started with a fresh database, and I still got errors, so it must be something on my side.

`[INFO] 2021-04-08 13:30:14 brs.db.sql.Db - Running flyway migration
[SEVERE] 2021-04-08 13:30:14 brs.Burst - org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected failed migration to version 3 (indirect incoming index). Please remove any half-completed changes then run repair to fix the schema history.
java.lang.RuntimeException: org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected failed migration to version 3 (indirect incoming index). Please remove any half-completed changes then run repair to fix the schema history.
        at brs.db.sql.Db.init(Db.java:143)
        at brs.Burst.loadWallet(Burst.java:188)
        at brs.Burst.init(Burst.java:166)
        at brs.Burst.main(Burst.java:150)
Caused by: org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected failed migration to version 3 (indirect incoming index). Please remove any half-completed changes then run repair to fix the schema history.
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:173)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
        at org.flywaydb.core.Flyway.execute(Flyway.java:570)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
        at brs.db.sql.Db.init(Db.java:140)
        ... 3 more
[INFO] 2021-04-08 13:30:14 brs.Burst - Shutting down...`

**Comment by Kafkamorph** [comment]
Confirmed - it was a mariadb version problem - "IF NOT EXISTS" on V3 and V4 migration/mariadb were not being handled. 
All good now.

**Comment by beezx** [comment]
I'm getting same error. How did you fix the issue?

Thanks for any info.

**Comment by Kafkamorph** [comment]
@beezx : I edited the V3__indirect_incoming_index.sql and V4__subscription_index.sql files (that are inside burst.jar in "db/migration_mariadb/" ), and got rid of "IF NOT EXISTS".

**Comment by jjos2372** [comment]
> @beezx : I edited the V3__indirect_incoming_index.sql and V4__subscription_index.sql files (that are inside burst.jar in "db/migration_mariadb/" ), and got rid of "IF NOT EXISTS".

That will require you to edit every future release too. Better to update your MariaDB or just use the H2 backend that is embedded and is the default for a while now.
