### ISSUE TITLE
Phoenix wallet eventually gets a screen to choose between it and classic but nothing happens 

### ISSUE THREAD

**Issue by paulpoco** [burst-apps-team/burstcoin#484]
Phoenix wallet eventually gets a screen to choose between it and classic but nothing happens when you click the selection. 
![Screenshot_20210408-073713_TeamViewer](https://user-images.githubusercontent.com/801414/114046724-f07bbc00-983d-11eb-958f-25b1d295a80e.jpg)
Only way to get Phoenix wallet back is to select it from BRS 3.0.0 again.

**Comment by paulpoco** [comment]
Also even if I have freshly opened Phoenix Wallet from BRS 3.0.0 and then hit refresh on the Browser the same screen comes up as my screenshot on the Github issue.

**Comment by ohager** [comment]
Humm, a routing problem with Angular, probably. I need to dig into it. To get back to the dashboard use `<host>/phoenix` (i.e. http://localhost:8125/phoenix) and remove eventually other parts of the url

thanks for reporting

**Comment by ohager** [comment]
Note to myself: Very prolly we need to use hash routing strategy for web builds!

**Comment by paulpoco** [comment]
http://localhost:8125/phoenix/dashboard doesn't refresh just get the screen with 2 selections.

http://localhost:8125/phoenix/ works

**Comment by ohager** [comment]
@paulpoco It is already fixed in phoenix wallet (applied hash routing) and will be rolled out with the next version of BRS.

**Comment by ohager** [comment]
Closing as new release V3.0.1 was rolled out together with Phoenix 1.1.0-beta.5 (although was fixed in beta.3 already)
