### ISSUE TITLE
Crowd Funding: Cached Details aren't refreshed in Wallet UI: Testnet

### ISSUE THREAD

**Issue by AussieDelly** [burst-apps-team/burstcoin#49]
The only way I can the see the latest details of a crowd funding project, after a pledge is received or status change is made, is to log out and back in again. I guess this empties some form of cache and the latest details are retrieved from the back end.

**Comment by shefass** [comment]
Crowd Funding will be removed from classic UI

**Comment by jjos2372** [comment]
Crowdfunds were smart contracts, no need to have it built-in in the wallet. It was removed on v3.0. People can build webpages for their crowdfunds or even some sort of service using BlockTalk ready to use contracts.
