### ISSUE TITLE
Transaction being sent despite not having enough BURST for it

### ISSUE THREAD

**Issue by EmeraldDay** [burst-apps-team/burstcoin#490]
So today I have tried making a commitment while one of my other commitments was still being processed, unaware of the consequences I pressed the "spend all" button (Phoenix Wallet) and what happened is that the transaction was still being processed after several hours, so I looked into it and it turned out I had less BURST than the commitment I sent. I think after sending the first commitment the balance just didn't lock BURST coins and it let me send them again. I don't have a transaction number cuz it just disappeared from my transactions tab when I sent another commitment with the right amount of coins.

**Comment by jjos2372** [comment]
Hello, thanks for reporting! This is already solved on commit 5a1e50c80c0e29494d37d5c709b4b8a4057507fd a few days ago. It will be on BRS v3.0.1 that should come out soon.

I'll leave it open until the release.

**Comment by ohager** [comment]
@jjos2372 closing as just released
