### ISSUE TITLE
Burst Explorer incorrect for block 890159, shows wrong pool

### ISSUE THREAD

**Issue by paulpoco** [burst-apps-team/burstcoin#499]
https://explorer.burstcoin.network/?action=account&account=5812913123670292755&submenu=blocks#

I won block 890159 at yabpool.com but the https://explorer.burstcoin.network say I was part of Onepool.
![Screenshot_20210605-183219_Chrome](https://user-images.githubusercontent.com/801414/120909695-717fe580-c62c-11eb-8aaa-5341090fba7d.jpg)

**Comment by frankTheTank72** [comment]
something to check for @Zoh63392187

**Comment by Zoh63392187** [comment]
This was a memcache issue when a fork happend.
This should be fixed now:
![image](https://user-images.githubusercontent.com/32987300/120919352-6de67000-c6b9-11eb-8593-f66b7c14b8d7.png)
