### ISSUE TITLE
Full Node - BRS.properties - P2P.myPlatform =

### ISSUE THREAD

**Issue by Viperlock** [burst-apps-team/burstcoin#505]
If you have an existing BURST- Prefix address and change the P2P.myPlatform = ""  to the new S- Prefix you are not getting paid for running a full node.

Changing my address to S-9L4Y-YAGH-A3F7-6UWTC returns this showing no payment being recived.

2021-06-16 21:06:34 | 65.186.10.106 | United States | 3.1.0 |  | No | 100&nbsp;%
-- | -- | -- | -- | -- | -- | --

Changed it back to BURST-9L4Y-YAGH-A3F7-6UWTC

2021-06-16 21:06:34 | 65.186.10.106 | United States | 3.1.0 | BURST-9L4Y-YAGH-A3F7-6UWTC | Yes | 100&nbsp;%
-- | -- | -- | -- | -- | -- | --

**Comment by jjos2372** [comment]
Hello, thanks for reporting, noted and mentioning the @Zoh63392187 that manages the award.

The award itself is not part of the protocol or part of the node software itself, so this issue will be closed soon.

**Comment by Zoh63392187** [comment]
Thanks for report @Viperlock . For future issue contact me on signum Discord directly or use the menu on the Explorer and select bugs. Thanks again.

Ohh btw it should be fixed :)
