### ISSUE TITLE
Cleaning up the repo

### ISSUE THREAD

**Issue by damccull** [burst-apps-team/burstcoin#513]
This repo is messy and it makes no sense that the main branch is a version number rather than 'master' or 'main'. I propose the following changes, in order, which should be easy to perform and will avoid losing data.

1. Branch 'master' to 'archive/old-master' or similar (old code, non-release branch)
2. Hard-reset 'master' to branch 'v3.0' (make this the current release branch)
3. Delete 'v2.5' branch (it's already merged and captured in a tag)
4. Rename 'gh-pages' to 'archive/gh-pages' (unmerged code, old code, non-release branch)
5. Rename 'develop' to 'archive/old-develop' (unmerged code, old code, non-release branch)
6. Rename 'llybin-sqlite-pr' to 'archive/llybin-sqlite-pr' (unmerged code, old code, non-release branch)
7. Rename 'harry1453/docker' to 'feature/harry1453/docker'
8. Rename 'jjos/3.1-polishing' to 'feature/jjos/3.1-polishing'
9. Rename 'jjos/beacon' to 'feature/jjos/beacon'
10. Rename 'jjos/sqlite' to 'feature/jjos/sqlite'
11. Rename 'jjos/sqlite2' to 'feature/jjos/sqlite2'
12. Rename 'feat/at-upgrade' to 'feature/at-upgrade'
13. Rename 'feat/jjos/nas' to 'feature/jjos/nas'
14. Rename 'v3.0' to 'develop'

These changes will result in a much cleaner repo without losing any data. Honestly, the things in the archive folder can probably go away, but I chose to keep them to provide a no-data-loss solution.

There is an example of what this repo can look like at my fork: https://github.com/damccull/burstcoin
*(Note: There is a branch folder called 'not-example' in my fork that should be ignored for the purposes of this proposal)*

This does not take into account any scripts that may directly reference branches by name. I believe most of the existing scripts reference release tags (Dockerfiles, for instance), but I can do a more thorough scrub if this proposal is accepted. Coming up with this took about an hour, so it should take only a few minutes to implement.

This should be done to help newcomers to the repo avoid confusion and to streamline the workflow. Features can be created on feature branches and merged into develop in order to test before release, or changes can be created directly on develop. Develop should then be merged into master and that merged commit should be tagged with the release version. That way the master branch will always be at the current release and an archive of releases will be maintained.

**Comment by jjos2372** [comment]
Repository will be moved soon to the new organization. When that comes we will have 'main' and 'devel', don't care about the feature branches.

**Comment by damccull** [comment]
Sounds good! Closing this as unnecessary, then
