### ISSUE TITLE
getGuaranteedBalance possible regression

### ISSUE THREAD

**Issue by blankey1337** [burst-apps-team/burstcoin#70]
From @zodi via Discord: Has something changed with the "getGuaranteedBalance" API call since 2.2.7?

Cause this works on a 2.2.7 wallet:
https://wallet.burst.cryptoguru.org:8125/burst?requestType=getGuaranteedBalance&account=BURST-GBFG-HVQ4-8AMM-GPCWR

and fails on 2.3.0:
https://swissburstcoin.internet-box.ch:8125/burst?requestType=getGuaranteedBalance&account=BURST-GBFG-HVQ4-8AMM-GPCWR

**Comment by harry1453** [comment]
Done as part of #57. Should have been documented... Oops.

Replacement is `getBalance` which is identical and existed before as well.
